server:
    port : 8088

api:
    prefix: api/v1

spring:
  application:
    name: library
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: minh
    password: minhpro
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: debug
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: debug